import {DeliveryIssueType, DeliveryOrder} from '../context/OrdersContext';

export type RootStackParamList = {
  Splash: undefined;
  Welcome: undefined;
  Login: undefined;
  RegistrationLanding: undefined;
  EnterMobileNumber: undefined;
  VerifyRegistrationOtp: {mobile: string; flow?: 'login' | 'register'};
  IncorrectOtp: {mobile: string; reason?: string; flow?: 'login' | 'register'};
  ResendOtpMethod: {mobile: string; flow?: 'login' | 'register'};
  AccountNotFound: {mobile: string};
  PersonalInformation: {mobile: string};
  ProfilePhoto: undefined;
  HomeAddress: undefined;
  EmergencyContact: undefined;
  VehicleType: undefined;
  VehicleDetails: {vehicleType: 'motorbike' | 'scooter' | 'bicycle' | 'other'};
  DrivingLicence: undefined;
  RcDocument: undefined;
  InsuranceDocument: undefined;
  PaymentDetails: undefined;
  ReviewApplication: {submitError?: string} | undefined;
  SubmittingApplication: undefined;
  ApplicationSubmitted: {referenceId: string};
  VerificationInProgress: undefined;
  RiderApproved: undefined;
  VerificationRejected: undefined;
  LocationPermission: undefined;
  LocationDenied: undefined;
  EnableNotifications: undefined;
  GPSDisabled: undefined;
  EnableGPSInstructions: undefined;
  FirstTimeSetup: undefined;
  HomeActiveDelivery: {orderId: string};
  AccountRestricted: undefined;
  NoInternet: undefined;
  Home: undefined;
  NewOrderRequest: {orderId: string};
  OrderRequestDetails: {orderId: string; secondsLeft?: number};
  RejectConfirmSheet: {orderId: string};
  RejectReason: {orderId: string};
  OrderRejected: {orderId: string; reason: string};
  RequestTimedOut: {orderId: string};
  MultipleOrders: undefined;
  NoOrdersInZone: undefined;
  AssignmentFailed: {orderId: string};
  AcceptingOrder: {orderId: string};
  OrderAccepted: {orderId: string};
  AssignedDelivery: {orderId: string};
  PickupDetails: {orderId: string};
  NavigateToStore: {orderId: string};
  NavigationActive: {orderId: string};
  ArrivingAtStore: {orderId: string};
  ConfirmingArrival: {orderId: string};
  ArrivedAtStore: {orderId: string};
  OrderReady: {orderId: string};
  OrderNotReady: {orderId: string};
  WaitingForOrder: {orderId: string};
  ReportStoreIssue: {orderId: string};
  ContactStore: {orderId: string};
  VerifyPickup: {orderId: string};
  OrderIdVerification: {orderId: string};
  PackageDetails: {orderId: string};
  CollectOrder: {orderId: string};
  PickupConfirmation: {orderId: string};
  OrderPickedUp: {orderId: string};
  PickupFailed: {orderId: string};
  PickupRetry: {orderId: string};
  PickupSupport: {orderId: string};
  CustomerStartNavigation: {orderId: string};
  CustomerNavigationActive: {orderId: string};
  NearCustomer: {orderId: string};
  ArrivedAtCustomer: {orderId: string};
  CallCustomer: {orderId: string};
  MessageCustomer: {orderId: string};
  DeliveryVerification: {orderId: string};
  DeliveryOtpIncorrect: {orderId: string};
  CustomerConfirmed: {orderId: string};
  HandOverOrder: {orderId: string};
  ConfirmingDelivery: {orderId: string};
  EarningsUpdated: {orderId: string};
  CustomerUnavailable: {orderId: string};
  CallingException: {orderId: string};
  NoResponse: {orderId: string};
  WaitingForCustomer: {orderId: string};
  CustomerContacted: {orderId: string};
  WrongAddress: {orderId: string};
  UpdateAddress: {orderId: string};
  CannotLocateCustomer: {orderId: string};
  OrderCancelledByCustomer: {orderId: string};
  StoreIssueDelivery: {orderId: string};
  MissingItemReported: {orderId: string};
  WrongItemInOrder: {orderId: string};
  PackageDamageDetected: {orderId: string};
  PackageIssue: {orderId: string};
  VehicleProblem: {orderId: string};
  RoadBlockage: {orderId: string};
  SafetyConcern: {orderId: string};
  CannotComplete: {orderId: string};
  ReportIssue: {orderId: string};
  SelectIssueReason: {orderId: string};
  UploadEvidence: {orderId: string; issueType: DeliveryIssueType};
  IssueSupportContact: {orderId: string; order?: DeliveryOrder};
  IssueResolution: {orderId: string; order?: DeliveryOrder};
  RetryDelivery: {orderId: string};
  ReturnOrder: {orderId: string};
  OrderReassigned: {orderId: string};
  DeliveryFailed: {orderId: string; order?: DeliveryOrder};
  DeliveryClosed: {orderId: string};
  CustomerDeliveryDetails: {orderId: string};
  OtpEntry: {orderId: string};
  DeliverySuccess: {orderId: string};
  EarningsDashboard: undefined;
  TodaysEarnings: undefined;
  DeliveryEarnings: {orderId: string};
  EarningsBreakdown: undefined;
  WeeklyEarnings: undefined;
  MonthlyEarnings: undefined;
  PaymentHistory: undefined;
  PayoutProcessing: undefined;
  PayoutSuccessful: undefined;
  PayoutFailed: undefined;
  BankUPIVerificationIssue: undefined;
  Incentives: undefined;
  IncentiveDetail: undefined;
  IncentiveProgress: undefined;
  IncentiveBonusEarned: undefined;
  BonusHistory: undefined;
  IncentiveExpired: undefined;
  Performance: undefined;
  DeliveriesCompleted: undefined;
  AcceptanceRate: undefined;
  CompletionRate: undefined;
  CustomerRating: undefined;
  WeeklyPerformance: undefined;
  MonthlyPerformance: undefined;
  DeliveryHistory: undefined;
  DeliveryHistoryDetail: {orderId: string};
  DeliveryHistoryEarnings: {orderId: string};
  OrderTimeline: {orderId: string};
  FailedDeliveries: undefined;
  Notifications: undefined;
  NotificationDetail: {id: string};
  Profile: undefined;
  ProfilePersonalInfo: undefined;
  ProfileEdit: undefined;
  ProfilePhotoEdit: undefined;
  ProfileAddress: undefined;
  ProfileEmergencyContact: undefined;
  VehicleHub: undefined;
  VehicleEdit: undefined;
  VehicleTypeChange: undefined;
  VehicleRegistration: undefined;
  VehicleRcDocument: undefined;
  VehicleInsurance: undefined;
  VehicleVerificationStatus: undefined;
  VehicleVerificationFailed: undefined;
  VehicleVerified: undefined;
  DocumentsHub: undefined;
  DocumentDrivingLicence: undefined;
  DocumentInsurance: undefined;
  DocumentOther: undefined;
  DocumentDetail: undefined;
  DocumentUpload: undefined;
  DocumentPreview: undefined;
  DocumentReplaceLicence: undefined;
  DocumentUnderReview: undefined;
  DocumentVerified: undefined;
  DocumentVerificationFailed: undefined;
  DocumentReUpload: undefined;
  PaymentHub: undefined;
  PaymentBankAccount: undefined;
  PaymentUpiDetails: undefined;
  PaymentAddBankAccount: undefined;
  PaymentEditBankDetails: undefined;
  PaymentBankVerificationStatus: undefined;
  PaymentBankVerificationFailed: undefined;
  PaymentBankVerified: undefined;
  PaymentUpiAdded: undefined;
  PaymentUpiVerificationFailed: undefined;
  SupportHub: undefined;
  SupportFaq: undefined;
  SupportDeliveryIssues: undefined;
  SupportPaymentIssues: undefined;
  SupportAccountIssues: undefined;
  SupportDocumentIssues: undefined;
  SupportVehicleIssues: undefined;
  SupportStoreIssues: undefined;
  SupportCustomerIssues: undefined;
  SupportTechnicalIssues: undefined;
  SupportOtherIssues: undefined;
  SupportSelectIssueType: undefined;
  TicketIssueDetails: undefined;
  TicketUploadEvidence: undefined;
  TicketReviewSubmit: undefined;
  TicketSubmitted: undefined;
  TicketDetail: undefined;
  TicketStatus: undefined;
  TicketChat: undefined;
  TicketResolved: undefined;
  TicketReopen: undefined;
  TicketEscalate: undefined;
  TicketClosed: undefined;
  AccountSecurity: undefined;
  AccountChangeMobileNumber: undefined;
  AccountVerifyNewNumber: undefined;
  AccountActiveSessions: undefined;
  AccountLogout: undefined;
  AccountLoggingOut: undefined;
  AccountNotificationSettings: undefined;
  AccountLocationSettings: undefined;
  AccountLanguageRegion: undefined;
  AccountPrivacy: undefined;
  AccountTerms: undefined;
  AccountPrivacyPolicy: undefined;
  AccountAbout: undefined;
  EmergencySafetyHub: undefined;
  EmergencyModeActive: undefined;
  EmergencyShareLocation: undefined;
  EmergencySupport: undefined;
  EmergencyIncidentReport: undefined;
  EmergencyIncidentReported: undefined;
  EmergencyResolved: undefined;
  DeactivateAccount: undefined;
  DeactivateReason: undefined;
  DeactivateActiveDeliveryBlock: undefined;
  DeactivateConfirm: undefined;
  DeactivateDone: undefined;
  StateSkeletonLoading: undefined;
  StateEmpty: undefined;
  StateNoDeliveries: undefined;
  StateServerError: undefined;
  StateGPSError: undefined;
  StateSessionExpired: undefined;
  StateAccessDenied: undefined;
  StateAccountSuspended: undefined;
  StateVerificationPending: undefined;
  StateVerificationFailed: undefined;
  StateUploadFailed: undefined;
  StateChangesNotSaved: undefined;
  StateActionFailed: undefined;
  StateGenericError: undefined;
  StateRetrying: undefined;
  StateSessionRecovery: undefined;
  StateSuccess: undefined;
  StateWarningInsurance: undefined;
};

declare global {
  namespace ReactNavigation {
    interface RootParamList extends RootStackParamList {}
  }
}
