import {DeliveryIssueType, DeliveryOrder} from '../context/OrdersContext';
import {DriverDocumentKey} from '../context/DriverAuthContext';

export type RootStackParamList = {
  Splash: undefined;
  Welcome: undefined;
  Login: undefined;
  RegistrationLanding: undefined;
  EnterMobileNumber: undefined;
  VerifyRegistrationOtp: {mobile: string; flow?: 'login' | 'register'};
  IncorrectOtp: {mobile: string; reason?: string; flow?: 'login' | 'register'; attemptsLeft?: number};
  ResendOtpMethod: {mobile: string; flow?: 'login' | 'register'};
  AccountNotFound: {mobile: string};
  PersonalInformation: {mobile: string};
  ProfilePhoto: undefined;
  HomeAddress: undefined;
  EmergencyContact: undefined;
  VehicleType: undefined;
  VehicleDetails: {vehicleType: 'motorbike' | 'scooter' | 'bicycle' | 'other'};
  DrivingLicence: undefined;
  RcDocument: undefined;
  InsuranceDocument: undefined;
  PaymentDetails: undefined;
  ReviewApplication: {submitError?: string} | undefined;
  SubmittingApplication: undefined;
  ApplicationSubmitted: {referenceId: string};
  VerificationInProgress: undefined;
  RiderApproved: undefined;
  VerificationRejected: undefined;
  LocationPermission: undefined;
  EnableNotifications: undefined;
  FirstTimeSetup: undefined;
  AccountRestricted: undefined;
  Home: undefined;
  HomeActiveDelivery: {orderId: string};
  NewOrderRequest: {orderId: string};
  OrderRequestDetails: {orderId: string; secondsLeft?: number};
  RejectConfirmSheet: {orderId: string};
  RejectReason: {orderId: string};
  OrderRejected: {orderId: string; reason: string};
  RequestTimedOut: {orderId: string};
  MultipleOrders: undefined;
  NoOrdersInZone: undefined;
  AssignmentFailed: {orderId: string};
  AcceptingOrder: {orderId: string};
  OrderAccepted: {orderId: string};
  PickupDetails: {orderId: string};
  NavigateToStore: {orderId: string};
  NavigationActive: {orderId: string};
  ArrivingAtStore: {orderId: string};
  ConfirmingArrival: {orderId: string};
  ArrivedAtStore: {orderId: string};
  OrderReady: {orderId: string};
  OrderNotReady: {orderId: string};
  WaitingForOrder: {orderId: string};
  ReportStoreIssue: {orderId: string};
  ContactStore: {orderId: string};
  VerifyPickup: {orderId: string};
  OrderIdVerification: {orderId: string};
  PackageDetails: {orderId: string};
  CollectOrder: {orderId: string};
  PickupConfirmation: {orderId: string};
  OrderPickedUp: {orderId: string};
  PickupFailed: {orderId: string};
  PickupRetry: {orderId: string};
  PickupSupport: {orderId: string};
  CustomerDeliveryDetails: {orderId: string};
  CustomerStartNavigation: {orderId: string};
  CustomerNavigationActive: {orderId: string};
  NearCustomer: {orderId: string};
  ArrivedAtCustomer: {orderId: string};
  CallCustomer: {orderId: string};
  MessageCustomer: {orderId: string};
  DeliveryVerification: {orderId: string};
  OtpEntry: {orderId: string};
  DeliveryOtpIncorrect: {orderId: string; attemptsLeft?: number; message?: string};
  HandOverOrder: {orderId: string};
  DeliverySuccess: {orderId: string};
  EarningsUpdated: {orderId: string};
  CustomerUnavailable: {orderId: string};
  CallingException: {orderId: string};
  NoResponse: {orderId: string};
  WaitingForCustomer: {orderId: string};
  CustomerContacted: {orderId: string};
  WrongAddress: {orderId: string};
  UpdateAddress: {orderId: string};
  CannotLocateCustomer: {orderId: string};
  OrderCancelledByCustomer: {orderId: string};
  StoreIssueDelivery: {orderId: string};
  WrongItemInOrder: {orderId: string};
  PackageDamageDetected: {orderId: string};
  PackageIssue: {orderId: string};
  VehicleProblem: {orderId: string};
  RoadBlockage: {orderId: string};
  SafetyConcern: {orderId: string};
  CannotComplete: {orderId: string};
  ReportIssue: {orderId: string};
  SelectIssueReason: {orderId: string};
  UploadEvidence: {orderId: string; issueType: DeliveryIssueType};
  IssueSupportContact: {orderId: string; order?: DeliveryOrder};
  IssueResolution: {orderId: string; order?: DeliveryOrder};
  RetryDelivery: {orderId: string};
  ReturnOrder: {orderId: string};
  DeliveryFailed: {orderId: string; order?: DeliveryOrder};
  DeliveryHistory: undefined;
  DeliveryHistoryDetail: {orderId: string};
  DeliveryHistoryEarnings: {orderId: string};
  OrderTimeline: {orderId: string};
  FailedDeliveries: undefined;
  EarningsDashboard: undefined;
  TodaysEarnings: undefined;
  DeliveryEarnings: {orderId: string};
  EarningsBreakdown: undefined;
  WeeklyEarnings: undefined;
  MonthlyEarnings: undefined;
  PaymentHistory: undefined;
  Incentives: undefined;
  IncentiveDetail: {incentiveId: string};
  IncentiveProgress: undefined;
  IncentiveBonusEarned: {incentiveId: string};
  BonusHistory: undefined;
  IncentiveExpired: undefined;
  Performance: undefined;
  DeliveriesCompleted: undefined;
  AcceptanceRate: undefined;
  CompletionRate: undefined;
  CustomerRating: undefined;
  Notifications: undefined;
  NotificationDetail: {id: string};
  Profile: undefined;
  ProfilePersonalInfo: undefined;
  ProfilePhotoEdit: undefined;
  ProfileAddress: undefined;
  ProfileEmergencyContact: undefined;
  VehicleHub: undefined;
  VehicleRegistration: undefined;
  VehicleRcDocument: undefined;
  VehicleInsurance: undefined;
  DocumentsHub: undefined;
  DocumentDetail: {docKey: DriverDocumentKey};
  DocumentPreview: {docKey: DriverDocumentKey};
  PaymentHub: undefined;
  PaymentBankAccount: undefined;
  PaymentUpiDetails: undefined;
  SupportHub: undefined;
  SupportFaq: undefined;
  SupportDeliveryIssues: undefined;
  SupportPaymentIssues: undefined;
  SupportAccountIssues: undefined;
  SupportDocumentIssues: undefined;
  SupportVehicleIssues: undefined;
  SupportStoreIssues: undefined;
  SupportCustomerIssues: undefined;
  SupportTechnicalIssues: undefined;
  SupportOtherIssues: undefined;
  AccountLogout: undefined;
  AccountPrivacy: undefined;
  AccountTerms: undefined;
  AccountPrivacyPolicy: undefined;
  AccountAbout: undefined;
  EmergencySafetyHub: undefined;
  EmergencyModeActive: {incidentId: string};
  EmergencyShareLocation: {incidentId?: string} | undefined;
  EmergencySupport: undefined;
  EmergencyIncidentReport: undefined;
  EmergencyIncidentReported: {incidentId: string};
  EmergencyResolved: {incidentId: string};
};

declare global {
  namespace ReactNavigation {
    interface RootParamList extends RootStackParamList {}
  }
}
